# CMake generated Testfile for 
# Source directory: /Volumes/hd2/pb2/build/sb_0-26796952-1516358398.63/mysql-connector-odbc-5.3.10-src/test
# Build directory: /Volumes/hd2/pb2/build/sb_0-26796952-1516358398.63/mysql-connector-odbc-5.3.10-src/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(my_basics "my_basics")
ADD_TEST(my_blob "my_blob")
ADD_TEST(my_bulk "my_bulk")
ADD_TEST(my_catalog1 "my_catalog1")
ADD_TEST(my_catalog2 "my_catalog2")
ADD_TEST(my_crash "my_crash")
ADD_TEST(my_curext "my_curext")
ADD_TEST(my_cursor "my_cursor")
ADD_TEST(my_datetime "my_datetime")
ADD_TEST(my_desc "my_desc")
ADD_TEST(my_dyn_cursor "my_dyn_cursor")
ADD_TEST(my_error "my_error")
ADD_TEST(my_info "my_info")
ADD_TEST(my_keys "my_keys")
ADD_TEST(my_param "my_param")
ADD_TEST(my_prepare "my_prepare")
ADD_TEST(my_relative "my_relative")
ADD_TEST(my_result1 "my_result1")
ADD_TEST(my_result2 "my_result2")
ADD_TEST(my_scroll "my_scroll")
ADD_TEST(my_setup "my_setup")
ADD_TEST(my_tran "my_tran")
ADD_TEST(my_types "my_types")
ADD_TEST(my_unicode "my_unicode")
ADD_TEST(my_unixodbc "my_unixodbc")
ADD_TEST(my_use_result "my_use_result")
ADD_TEST(my_bug13766 "my_bug13766")
ADD_TEST(my_pooling "my_pooling")
ADD_TEST(my_auth "my_auth")
